-- 연습용 db 생성 
CREATE DATABASE mydb;

use mydb;

-- 학생, 과목 , 수강 테이블을 만들고 직접 샘플 값을 넣어 보세요.

-- 학생 테이블 
CREATE TABLE STUDENT (
	STUDENT_ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    GRADE INT NOT NULL,
    MAJOR VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20)
);

-- 과목 테이블
CREATE TABLE SUBJECT(
	SUBJECT_ID INT PRIMARY KEY,
    SUBJECT_NAME VARCHAR(50) NOT NULL,
    CREDIT INT NOT NULL,
    PROFESSOR VARCHAR(30) NOT NULL
);

-- 수강 테이블
CREATE TABLE ENROLLMENT(
	
    ENROLLMENT_ID INT PRIMARY KEY,
    STUDENT_ID INT NOT NULL, 
    SUBJECT_ID INT NOT NULL,
    SCORE DECIMAL(5,2),
    ENROLLED_AT DATE  NOT NULL,
    FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECT(SUBJECT_ID)
    
);

SELECT * FROM ENROLLMENT;